[build]
  publish = "netlify"

[build.environment]
  PYTHON_VERSION = "3.11"
  PIP_REQUIREMENTS = "netlify/empty_requirements.txt"

[[edge_functions]]
  path = "/*"
  function = "proxy"

[[redirects]]
  from = "/*"
  to = "https://www.marketaioctobot.com/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/github"
  to = "https://github.com/ShannenJael/Octobot_Server"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
