[build]
  publish = "netlify"

[[edge_functions]]
  path = "/*"
  function = "proxy"

[[redirects]]
  from = "/github"
  to = "https://github.com/ShannenJael/Octobot_Server"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
